var GAME_LEVELS = [
  ["                                                                          ",
   "                                                                          ",
   "                                                   y                      ",
   "                                                                          ",
   "            x!!!x          y                 x    xxx                     ",
   "  y         xxxxx                            x     x                      ",
   "                          xxx                x     x                      ",
   "xxxxx                                        x     xxxxx                  ",
   "!!!!!                x!!!!!!!!!!!x           xx    x                      ",
   "!!!!!xxx             x!!!!!!!!!!!x           x     x         y            ",
   "!!!!!                xxxxxxxxxxxxx                 x                      ",
   "!!!!!           #                                  x                      ",
   "!!!!!  y                                           x!!!!!!!xxxxx          ",
   "!!!!!       xxxxx                                xxxxxxxxxx               ",
   "!!!!!                                          !!!!x                      ",
   "!!!!!xxxxx             ~                xxxxxxxxxxxx                y     ",
   "xxxxxx                                                                    ",
   "                xxxxxxxxxxx                                               ",
   "                               $                                          ",
   "                              xxx                                         ",
   "                                                                          ",
   "                                              y                  xxxxxxx  ",
   "     xxx     xxxx                  xxxxxx                  y     x!!!!!!!!",
   "     x       x                     x        xxxxx                x!!!!!!!!",
   "@    x!!!!!!!x!!!!!!x           y  x                            xx!!!!!!!!",
   "xxxxxx!!!!!!!x!!!!!!x              x    xx                       x!!!!!!!!",
   "xxxxxxxxxxxxxxxxxxxxxxxx      xxxxxx    x!!!!!!!!!x              x!!!!!!!!",
   "                                        x!!!!!!!!!x    xxxxxxxxxxx!!!!!!!!",
   "                                        x!!!!!!!!!x    x!!!!!!!!!!!!!!!!!!",
   "         y                xx          xxx!!!!!!!!!x    x!!!!!!!!!!!!!!!!!!",
   "                                        x!!!!!!!!!x    x!!!!!!!!!!!!!!!!!!",
   "                                        xxxxxxxxxxx   xx!!!!!!!!!!!!!!!!!!",
   "              xxx               xx                     x!!!!!!!!!!!!!!!!!!",
   "!!!!!!!xxxxx!!!!!!!xxxxx                    y   y      x!!!!!!!!!!!!!!!!!!",
   "!!!!!!!xxxxx!!!!!!!xxxxx                               x!!!!!!!!!!!!!!!!!!",
   "!!!!!!!xxxxx!!!!!!!xxxxx                               x!!!!!!!!!!!!!!!!!!",
   "!!!!!!!xxxxx!!!!!!!xxxxx!!!!!!!!!!!!xxxxx!!xx!!!xx!!xxxx!!!!!!!!!!!!!!!!!!"],
  ["                                                                          ",
   "                                                                          ",
   "                             y                                            ",
   "                         xxxxxxxxx                                        ",
   "  y                                                                   y   ",
   "                 xxxxx!!!!!!!!!!!!!!!xxxxx                                ",
   "                   xx                                                     ",
   "                   x                                                      ",
   "       xxxxxx      x                                                xxxxx ",
   "       !!!!!!      x                         $                            ",
   "                 x x                xxxxxxxxxxxx                #         ",
   "                   x         y           x     x         xxxxxxxxxxxx     ",
   "                   x                     x     x                          ",
   "                   x                     x     x                          ",
   "     xxxxxxxxxxxxxxx!!!!!!!xxxxx!!!!!!!!!x     x  ~                       ",
   "     x             xxxxxxxxxxxxxxxxxxxxxxx     xxxxx      y               ",
   "     x                                         x                          ",
   "  y xx                                         x                          ",
   "                                               x                          ",
   "                                               x!!!!!!!!!!xx              ",
   "xxxxxx                                         xxxxxxxxxxxxxx             ",
   "!!!!!x                                                              y     ",
   "                                                                          ",
   "                                          y                               ",
   "        xxxxx                                                             ",
   "        x                                               xxxxxx!!xxxxxxxxxx",
   "        x               y                               x!!!!!!!!!!!!!!!!!",
   "       xx                                xxx            x!!!!!!!!!!!!!!!!!",
   "        x      xxxxx                                    x!!!!!!!!!!!!!!!!!",
   "        x                                               x!!!!!!!!!!!!!!!!!",
   "        x                                     y  xxxxxxxx!!!!!!!!!!!!!!!!!",
   "@       x                                        !!!!!!!!!!!!!!!!!!!!!!!!!",
   "xxxxxxxxx  y          xxxxxxxxxxx                !!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!                                        !!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!        xxxx                    xxx     !!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"],
  ["                                                                          ",
   "                                                                          ",
   "                                                                          ",
   "        y              xxxxxxxxxx     xxxxxxx              y              ",
   "       xxx             x    x!!!!    x!!!!x                               ",
   "@                xxxxxxx    x!!!!     !!!!x      xxxxx                    ",
   "xxxxx!!!!!!!!x              x!!!!     !!!!x              xxxxx            ",
   "    x!!!!!!!!x              x!!!!x y  !!!!x                               ",
   " y  xxxxxxxxxx              x!!!!     !!!!x                               ",
   "                            x!!!!     !!!!x                               ",
   "                            xxxxxxxxxxxxxxxxxxx                           ",
   "                                                                          ",
   "                                                                          ",
   "!xx!xxxx                         y                  $                     ",
   "!!!!!!!!                                          xxxxx                   ",
   "!!!!!!!!                      xxxxxx              x        xx    y        ",
   "!!!!!!!!xxx                                     xxx                       ",
   "                          #                                               ",
   "                     xxxxxx            xxxxxx                  xxxxx      ",
   "               y     x!!!!!!!!!!!!!!!!!x                                  ",
   "              xxx    x!!!!!!!!!!!!!!!!!x                                  ",
   "              x      x!!!!!!!!!!!!!!!!!x                                  ",
   "              x      x!!!!!!!!!!!!!!!!!x                                  ",
   "             xx      x                                                    ",
   "                     x                                 xxxx               ",
   "                     x                                    x               ",
   "     y    xxxxx!!!!!!x        y                           x               ",
   "    xxx       xxxxxxxx                                    xx    y         ",
   "                                                                          ",
   "            y                                                             ",
   "xx                                                                        ",
   "                            xxxxxx     ~                                  ",
   "                                              y            xxx!!!!!xxx    ",
   "          xxxxx       y              xxxxx                   xxxxxxxxxx   ",
   "                                                     xx      x            ",
   "                                                     x!!!!!!!x     y      ",
   "                   xxxxxxx                   xxxxxxxxx!!!!!!!x            ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x            ",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxx"],
  ["                                                                          ",
   "                                                                          ",
   "  x    x   xx   x x                                                       ",
   "   x  x   x  x  x x                                                       ",
   "    xx    x  x  x x                                                       ",
   "    xx     xx   xxx                                                       ",
   "                                                                          ",
   "  x   x  x  x  x  x  x                                                    ",
   "  x   x  x  xx x  x  x                                                    ",
   "  x x x  x  x xx                                                          ",
   "  xxxxx  x  x  x  x  x                                                    ",
   "                x      x                                                  ",
   "                x      x                                                  ",
   "                xxxxxxxx                                                  ",
   "                                                                          ",
   "                                                                          ",
   "                                                                          "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
